# Generated by Django 4.1.5 on 2023-03-16 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TV_State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.IntegerField(default=1, verbose_name='state')),
                ('tv_dis_state', models.BooleanField(default=False)),
                ('tv_power_state', models.BooleanField(default=False)),
                ('start_time', models.TimeField(default=datetime.time(6, 0))),
                ('stop_time', models.TimeField(default=datetime.time(15, 0))),
            ],
        ),
        migrations.CreateModel(
            name='upload_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(blank=True, null=True, unique=True, upload_to='data/')),
                ('name', models.TextField(null=True, unique=True, verbose_name='name')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
            ],
        ),
    ]
