# Generated by Django 4.1.5 on 2023-03-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoDisplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_state',
            name='tv_power_tgl',
            field=models.BooleanField(default=False),
        ),
    ]
