# Generated by Django 4.1.5 on 2023-03-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoDisplay', '0002_tv_state_tv_power_tgl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tv_state',
            name='tv_dis_state',
        ),
        migrations.RemoveField(
            model_name='tv_state',
            name='tv_power_state',
        ),
        migrations.RemoveField(
            model_name='tv_state',
            name='tv_power_tgl',
        ),
        migrations.AddField(
            model_name='tv_state',
            name='last_state',
            field=models.IntegerField(default=1),
        ),
    ]
