# Generated by Django 4.1.5 on 2023-03-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoDisplay', '0003_remove_tv_state_tv_dis_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_state',
            name='r_dis_state',
            field=models.BooleanField(default=False),
        ),
    ]
